name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e .[dev]
      # Gates in same order as `make check`
      - run: python -m black . --line-length 100 --check
      - run: python -m isort . --profile black --line-length 100 --check-only
      - run: flake8
      - run: mypy acmecli
      - run: coverage run -m pytest tests/ -q
      - run: coverage report -m
