name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -e .[dev]
      - run: flake8
      - run: isort --check-only .
      - run: mypy acmecli
      - run: coverage run -m pytest -q
      - run: coverage report -m
